@startuml
    folder "src" as src_b874d07 {
      card msh_node_env_return_e4daf83f [
        MshNodeEnvReturn
        ---
        (name: string) => EnvFactory
      ]
      object "MshNodeEnv" as msh_node_env_e4daf83f {
      }
      folder "convert" as convert_1954ac1f {
        class "Base64ToString" as base64_to_string_13880200 {
          + convert(str?: string): string | undefined
        }
        interface "ConvertStrategy" as convert_strategy_8da53918 {
          + convert(str?: string): T | undefined
        }
        class "ToBoolean" as to_boolean_d7e3630b {
          + convert(str?: string): boolean | undefined
        }
        class "ToJson" as to_json_6938b317 {
          + convert(str?: string): T | undefined
        }
        class "ToNumber" as to_number_d46587ec {
          + convert(str?: string): number | undefined
        }
        class "ToString" as to_string_5ce920da {
          + convert(str?: string): string | undefined
        }
      }
      folder "env" as env_339e04b5 {
        class "EnvFactory" as env_factory_eea4fbf7 {
          # _env: Env
          + base64: EnvType<string>
          + boolean: EnvType<boolean>
          constructor(params: {\n name: string;\n locationStrategies: LocationStrategy[];\n namingStrategies: NamingStrategy[] \n})
          + json: EnvType<T>
          + number: EnvType<number>
          + string: EnvType<string>
        }
        class "EnvType" as env_type_5c8a31bb {
          # _EnvName: string
          # _allowedValues: T[]
          # _allowedValuesDoNotContain(value?: T): boolean
          # _allowedValuesToString: string
          # _convertStrategy: ConvertStrategy<T>
          # _createError(msg: string): Error
          # _defaultValue: T | undefined
          # _env: Env
          # _loggerDebug(msg: string,\n ...args: {\n [k: string]: any \n}[]): void
          # _validateAllowedValues(value?: T): void
          + allowed(...args: T[]): EnvType<T>
          + constructor(params: {\n convertStrategy: ConvertStrategy<T>;\n env: Env \n})
          + default(defaultValue: T): EnvType<T>
          + optional: T | undefined
          + required: T
        }
        class "Env" as env_bbdfdbee {
          + Name: string
          # _envNames: string[]
          # _locationStrategies: LocationStrategy[]
          # _name: string
          # _namingStrategies: NamingStrategy[]
          + constructor(params: {\n name: string;\n locationStrategies: LocationStrategy[];\n namingStrategies: NamingStrategy[] \n})
          + envValue: string | undefined
        }
      }
      folder "location" as location_7620ea55 {
        class "DockerSecretsLocation" as docker_secrets_location_d5fdf29f {
          + valueByName(name: string): string | undefined
        }
        class "EnvironmentLocation" as environment_location_e89f1336 {
          + valueByName(name: string): string | undefined
        }
        interface "LocationStrategy" as location_strategy_a00e57d8 {
          + valueByName(name: string): string | undefined
        }
      }
      folder "naming" as naming_137c488a {
        interface "NamingStrategy" as naming_strategy_7c8902f8 {
          + names(name: string | string[]): string[]
        }
        class "PrefixName" as prefix_name_67a7c3f6 {
          # _prefix: string
          + constructor(prefix: string)
          + names(nameOrNames: string | string[]): string[]
        }
        class "SimpleName" as simple_name_bdd42ce8 {
          + names(nameOrNames: string | string[]): string[]
        }
        class "SuffixName" as suffix_name_13ec6f31 {
          # _suffix: string
          + constructor(suffix: string)
          + names(nameOrNames: string | string[]): string[]
        }
      }
    }
  base64_to_string_13880200 .up.|> convert_strategy_8da53918
  to_boolean_d7e3630b .up.|> convert_strategy_8da53918
  to_json_6938b317 .up.|> convert_strategy_8da53918
  to_number_d46587ec .up.|> convert_strategy_8da53918
  to_string_5ce920da .up.|> convert_strategy_8da53918
  env_factory_eea4fbf7 -up-> base64_to_string_13880200
  env_factory_eea4fbf7 -up-> to_boolean_d7e3630b
  env_factory_eea4fbf7 -up-> to_json_6938b317
  env_factory_eea4fbf7 -up-> to_number_d46587ec
  env_factory_eea4fbf7 -up-> to_string_5ce920da
  env_factory_eea4fbf7 -up-> env_bbdfdbee
  env_factory_eea4fbf7 -up-> env_type_5c8a31bb
  env_type_5c8a31bb -up-> convert_strategy_8da53918
  env_type_5c8a31bb -up-> env_bbdfdbee
  env_type_5c8a31bb -up-> env_type_5c8a31bb
  msh_node_env_e4daf83f -up-> env_factory_eea4fbf7
  msh_node_env_e4daf83f -up-> msh_node_env_return_e4daf83f
  docker_secrets_location_d5fdf29f .up.|> location_strategy_a00e57d8
  environment_location_e89f1336 .up.|> location_strategy_a00e57d8
  prefix_name_67a7c3f6 .up.|> naming_strategy_7c8902f8
  simple_name_bdd42ce8 .up.|> naming_strategy_7c8902f8
  suffix_name_13ec6f31 .up.|> naming_strategy_7c8902f8
@enduml