version: v1.0
name: Prod Deploy
agent:
  machine:
    type: e1-standard-2

  containers:
    - name: main
      image: 'registry.semaphoreci.com/node:14'
blocks:
  - name: Deploy to Production
    task:
      secrets:
        - name: bc-msh-node-env-secret
      jobs:
        - name: Deploy
          commands:
            - cache restore bc-msh-node-env-version-$SEMAPHORE_GIT_SHA
            - export $(cat version.txt)
            - rm version.txt
            - checkout
            - git remote rm origin
            - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/beecode-rs/msh-node-env.git
            - git checkout tags/v$VERSION -b tmp-prod-branch
            - git tag v$VERSION-prod && git push origin --tags
            - npm publish
    skip:
      when: branch != 'main'
